import React from 'react';

const Courses = () => {
    return (
        <div>
            <h1>This is Courses</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste vel cumque inventore, omnis nemo suscipit rerum magni rem hic voluptate est dolorum reprehenderit minima nihil maxime officia molestiae cum explicabo! Similique, dolore, ullam veritatis repellat dicta maxime possimus et distinctio ab dignissimos deserunt non natus consequuntur magnam repellendus! Pariatur, sed.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste vel cumque inventore, omnis nemo suscipit rerum magni rem hic voluptate est dolorum reprehenderit minima nihil maxime officia molestiae cum explicabo! Similique, dolore, ullam veritatis repellat dicta maxime possimus et distinctio ab dignissimos deserunt non natus consequuntur magnam repellendus! Pariatur, sed.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste vel cumque inventore, omnis nemo suscipit rerum magni rem hic voluptate est dolorum reprehenderit minima nihil maxime officia molestiae cum explicabo! Similique, dolore, ullam veritatis repellat dicta maxime possimus et distinctio ab dignissimos deserunt non natus consequuntur magnam repellendus! Pariatur, sed.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste vel cumque inventore, omnis nemo suscipit rerum magni rem hic voluptate est dolorum reprehenderit minima nihil maxime officia molestiae cum explicabo! Similique, dolore, ullam veritatis repellat dicta maxime possimus et distinctio ab dignissimos deserunt non natus consequuntur magnam repellendus! Pariatur, sed.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste vel cumque inventore, omnis nemo suscipit rerum magni rem hic voluptate est dolorum reprehenderit minima nihil maxime officia molestiae cum explicabo! Similique, dolore, ullam veritatis repellat dicta maxime possimus et distinctio ab dignissimos deserunt non natus consequuntur magnam repellendus! Pariatur, sed.</p> <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste vel cumque inventore, omnis nemo suscipit rerum magni rem hic voluptate est dolorum reprehenderit minima nihil maxime officia molestiae cum explicabo! Similique, dolore, ullam veritatis repellat dicta maxime possimus et distinctio ab dignissimos deserunt non natus consequuntur magnam repellendus! Pariatur, sed.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste vel cumque inventore, omnis nemo suscipit rerum magni rem hic voluptate est dolorum reprehenderit minima nihil maxime officia molestiae cum explicabo! Similique, dolore, ullam veritatis repellat dicta maxime possimus et distinctio ab dignissimos deserunt non natus consequuntur magnam repellendus! Pariatur, sed.</p> <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste vel cumque inventore, omnis nemo suscipit rerum magni rem hic voluptate est dolorum reprehenderit minima nihil maxime officia molestiae cum explicabo! Similique, dolore, ullam veritatis repellat dicta maxime possimus et distinctio ab dignissimos deserunt non natus consequuntur magnam repellendus! Pariatur, sed.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste vel cumque inventore, omnis nemo suscipit rerum magni rem hic voluptate est dolorum reprehenderit minima nihil maxime officia molestiae cum explicabo! Similique, dolore, ullam veritatis repellat dicta maxime possimus et distinctio ab dignissimos deserunt non natus consequuntur magnam repellendus! Pariatur, sed.</p>
        </div>
    );
};

export default Courses;